### ISSUE TITLE
Missing 'mars.api' Files for Experimentation

### ISSUE THREAD

**Issue by elated-sawyer** [XiaojuanTang/Mars#1]
Hello,

First, I want to express my deep admiration for the excellent work you've done on the MARS environment. The work is truly impressive, and I appreciate all the effort and dedication that went into creating it.

As I work with the provided baseline model, I noticed that the `mars.api` files seem to be missing or unavailable. Without these files, it appears challenging to fully utilize the environment, especially for implementing and testing new algorithm designs. Could you kindly clarify if there are plans to release these files or if there’s an alternative way to access them?

Thank you for your time and support. I greatly appreciate the opportunity to work with such a fantastic env and look forward to your response.

**Comment by XiaojuanTang** [comment]
Thank you for your interest in our work and for bringing this to our attention. We have now uploaded the `mars.api` files.

**Comment by elated-sawyer** [comment]
> Thank you for your interest in our work and for bringing this to our attention. We have now uploaded the `mars.api` files.

Thank you for the quick response and for uploading the `mars.api` files!
